baseurl             = "https://you.github.io/"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
languageCode        = "en-US"
layoutdir           = "layouts"
publishdir          = "public"
theme = "cocoa-hugo-theme"
author              = "John A. Bernau"
title               = "John A. Bernau"
pygmentsuseclasses  = true
#disqusshortname     = "cocoaexamplesite" # Comment out to disable Disqus.
pluralizelisttitles = false
googleAnalytics     = ""

[permalinks]
blog  = "blog/:slug/"

[[menu.main]]
name                   = "research"
weight                 = 1
identifier             = "research"
url                    = "/xresearch/"

[[menu.main]]
name                   = "Teaching"
weight                 = 2
identifier             = "teaching"
url                    = "/xteaching/"


[[menu.main]]
name                   = "Blog"
weight                 = 3
identifier             = "blog"
url                    = "/blog/"

[[menu.main]]
name                   = "Code"
weight                 = 4
identifier             = "code"
url                    = "/xcode/"

[[menu.main]]
name                   = "About"
weight                 = 5
identifier             = "about"
url                    = "/about/"

[[menu.main]]
name                   = "CV"
weight                 = 6
identifier             = "cv"
url                    = "/img/Bernau_CV_2018.pdf"



[params]
include_rss            = false   # include RSS <link> tag in <head> and show RSS icon
latestpostscount       = -1      # how many posts to display on the home page
i18n_flags             = false   # whether to display small country flags for available translations
author                 = "John A. Bernau"
cachebuster            = true      # add the current unix timestamp in query string for cache busting css assets
dateform               = "Jan 2, 2006"
dateformfull           = "Mon Jan 2 2006 15:04:05 MST"
description            = "Don't panic"
email                  = "john.bernau@emory.edu"
extracssfiles          = [ "/css/override.css" ]       # In your `static` directory, add/remove files as necessary.
faviconfile            = ""
github                 = "https://github.com/johnbernau"
instagram              = ""
px500                  = ""
lang                   = "en"
linkedin               = "https://www.linkedin.com/in/john-bernau-b384a9153"
noshowreadtime         = true     # if true, don't show "<x> minutes read" in posts
selfintro              = "PhD Candidate, Sociology"    # appears in the site header when set to a non-empty string
twitter                = ""
mastodon               = ""

highlightjs            = true
# highlightjslanguages = ["go"]                        # additional languages not included in the "common" set
# highlightjsStyle     = "darcula"

piwik                  = false                         # If true, Piwik integration is enabled
# piwik_url            = ""    # URL to your Piwik installation. Must End with a slash
# piwik_id             =                              # Id of your site in Piwik

gitalk                 = false
# if gitalk is true, the following params should be set. These parameters could be retrieved from github OAuth
gitalk_clientID        = "your client id"
gitalk_clientSecret    = "your client secret"
gitalk_repo            = "your repo url"
gitalk_owner           = "the owner of this repo"
gitalk_admin           = ['a', 'list', 'of', 'administrator']

avatar  = "img/fb2.jpg" # path to image in static dir e.g img/avatar.png (do not use in the same time as gravatar)
# gravatar  = ""                # gravatar hash. see https://en.gravatar.com/site/implement/hash/. do not use in the same time as avatar

# The following are DEPRECATED.
gatracker              = "XYZ" # use googleAnalytics instead
initials               = "ad"  # displayed on single post page; deprecated in v0.3.0.
