---
title: "The Sympathetic Leviathan: How Do Modern States Culturally Respond to Disasters"
author: John A. Bernau
date: 2018-04-01T21:13:14-05:00
slug: sympathetic-leviathan
categories: []
tags: []
---

[Bin Xu](https://binxu.net/) & [John A. Bernau](https://johnabernau.netlify.com/about/)  
  
ABSTRACT: While events are central to the sociology of the state, natural disasters, a type of events with substantive and theoretical significance, have received scant attention. To address this gap, we theorize states’ cultural response to disasters—how states use discourses and actions to address moral and political meanings of death and suffering. We borrow insights from a few strands of scholarship: the sociology of disaster, cultural sociology of the state, and cultural theories of trauma and theodicy. We integrate them into a dramaturgical framework and compare two massive disasters—the Sichuan earthquake in China and Hurricane Katrina in the United States. We examine how the two states were engaged in struggles for meanings and explain features and outcomes of their performance by dramaturgical factors. This article also improves the cultural sociology of the state by extending it to the realm of existential meanings about citizens’ life, death, pain, and suffering. 

*Under Review* April 2018