---
title: "Overlapping Shootings"
author: "John Bernau"
date: "9/21/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(out.height='1000px', out.width = '1000', dpi=200)
```

In a 30-day window there are 37 events that have some degree of overlap: 
```{r, echo = F, message = F}
load("/Users/johnbernau/Box Sync/1. Desktop/3. Publications/Google_Search_Data/Analysis/9.19.18 session/gc_joined.RData")
require(tidyverse)
require(broom)
require(plotly)

#ggplot(t, aes(factor(date3))) + geom_histogram(stat = "count")

# Return all the overlap days
dates <- count(t, date3, sort = T) %>%  filter(n != 1)

e <- select(t, id, case, date, date3, days_after)
f <- inner_join(e, dates)

# Events with overlap
oe <- count(f, case)

# full dataset of only the events that have overlap
foe <- filter(t, case %in% oe$case) %>% 
  mutate(year = str_sub(date3, 1, 4))

foe$id <- as.factor(foe$id)
foe$id <- reorder(foe$id, desc(foe$date3))
p <- ggplot(foe, aes(date3, id, color = case)) + 
  geom_line(aes(group = id, alpha = total_victims)) +
  scale_color_discrete(guide = F) +
  scale_alpha_continuous(range = c(0.9,1), guide = F) +
  facet_wrap(~year, scales = "free", ncol = 2)
ggplotly(p)
```

___  
___  
  
In a 7-day window there are 15 events that have some degree of overlap: 
```{r, echo = F, message = F}

# Only in a 7 day window

sd <- filter(t, days_after < 8)
# Return all the overlap days
dates <- count(sd, date3, sort = T) %>%  filter(n != 1)

e <- select(sd, id, case, date, date3, days_after)
f <- inner_join(e, dates)

# Events with overlap
oe <- count(f, case)

# full dataset of only the events that have overlap
foe <- filter(t, case %in% oe$case) %>% 
  mutate(year = str_sub(date3, 1, 4))

foe$id <- as.factor(foe$id)
foe$id <- reorder(foe$id, desc(foe$date3))
p <- ggplot(foe, aes(date3, id, color = case)) + 
  geom_line(aes(group = id, alpha = total_victims)) +
  scale_color_discrete(guide = F) +
  scale_alpha_continuous(range = c(0.9,1), guide = F) +
  facet_wrap(~year, scales = "free", ncol = 2)
ggplotly(p)
```


___

### *Copyright &copy; 2018 John A. Bernau*
